### ISSUE TITLE
charles__cheerful - Account Abstraction wallet cant claim prize

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#122]
charles__cheerful

High

# Account Abstraction wallet cant claim prize

### Summary

If the winner is a smart contract implementing account abstraction, it might not be able to claim the prize as they might not own the same address in Ethereum mainnet. 

### Root Cause

Account abstraction wallets can have different addresses in different chains. A smart contract address implementing account abstraction in Avalanche might not be owned by the same person in Ethereum mainnet.

### Internal pre-conditions

Does not apply.

### External pre-conditions

Does not apply.

### Attack Path

1. _AA_ (Account Abstraction) wallet buys points and they are minted to `msg.sender`.
2. _AA_ wallet wins a prize.
3. The prize is `propagateRaffleWinner()` which will use as winner the `msg.sender` saved on `_ticketOwnership` map on the `WinnablesTicket` contract to set that address as the winner on Ethereum through CCIP. 
4. CCIP is successful and the winner is set on Ethereum. However that address might be owned by no-one or someone else.

### Impact

Someone else wins the lottery or even worse funds are stuck there forever until someone manages to figure out a way of getting that address in Ethereum. This can be forever.

### PoC

The winner in `propagateRaffleWinner()` is taken from the `_ticketOwnership` map on the `WinnablesTicket` contract trhough the `ownerOf()`. See [here](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L338), then [here](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L476), and then [here](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L100).

This value was set as `msg.sender` when minting the tokens through the `buyTickets()` [here](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L208). See minting function [here](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicket.sol#L194).

### Mitigation

Allow the winner to chose a destination address before propagating.

**Comment by CarlosAlegreUr** [comment]
Escalate

If someone interacts with the code with an AA wallet it will clearly lose its prize. Why has this been invalidated?

**Comment by SovaSlava** [comment]
Agree with escalation.  it could be even other situation - multisig contract, when user purchase ticket. But on Eth mainnet he is not owner of this multisig.

The same Valid issue -  https://codehawks.cyfrin.io/c/2024-01-Morpheus/s/239/

**Comment by Joshuajee** [comment]
My issue is a duplicate of https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/179

**Comment by SovaSlava** [comment]
My too - [456](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/456)

**Comment by S3v3ru5** [comment]
#294

**Comment by ebok21** [comment]
Tagging my issue - #609

**Comment by mosharaf6** [comment]
#307 
is a duplicate of this issue

**Comment by johnson37** [comment]
[#99 ](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/99)
is a duplicate of this issue.

**Comment by PeterSRWeb3** [comment]
Another duplicate https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/321

**Comment by mystery0x** [comment]
This has been discussed with the HOJ agreeing that this commonly known issue non-rewarded and something the protocol chooses not to fix. Users should know ahead of time whether or not the receiving address is the same as the sending address. AA is that generally validation can include any logic. EIP4337 for instance allows that as well (any limitations on the validation step are purely done off-chain and not guaranteed by the protocol).

**Comment by WangSecurity** [comment]
Yeah, users who use AA wallets should be aware that they don't own the same address on different chains. Hence, I agree it should be low severity. But, I would be glad to hear the opposite side as well.

**Comment by CarlosAlegreUr** [comment]
> This has been discussed with the HOJ agreeing that this commonly known issue non-rewarded and something the protocol chooses not to fix. Users should know ahead of time whether

I respect your point of view and it is true that this is kind of a design choice and a user responsibility. 

I just want to mention that if we want crypto to get into the masses we must make users have to worry of as little thing as possible. While not a bug this is in my opinion a pretty bad design choice and I do think these kind of "low-issues" provide value and should be rewarded. 

I get that according to the rules of Sherlock it is not rewardable and I thank judges for the explanation. I'm just giving my opposite side opinion as requested. Thanks for your time. `:D`

**Comment by SovaSlava** [comment]
@mystery0x  Such a restriction (users being unable to use the project if they use a multisig wallet) represents a loss of potential revenue for the project. Therefore, I think it can be classified as a medium issue.

Another valid issue about this subjet:
https://solodit.xyz/issues/m-02-all-bridged-funds-will-be-lost-for-the-users-using-the-account-abstraction-wallet-code4rena-ondo-finance-ondo-finance-git

**Comment by WangSecurity** [comment]
After additionally considering this issue, I agree that it should be a valid medium. Even though the AA owner should know they have different addresses on different chains, this issue leads to AA wallets not being able to participate in Raffles. Planning to accept the escalation and validate with medium severity.

This issue will be the main one, here are the duplicates:
- #318 
- #260 
- #193
- #179
- #609 
- #307 
- #99
- #157 
- #255 
- #241
- #164
- #319 
- #166
- #594
- #606

There are some other mentioned duplicates, which I believe are not sufficient. The first group is about using contracts for interacting with Winnables, it's invalid as a user mistake and they should be aware that when they deploy contracts on different chains, these contracts have different addresses, unlike AA wallets, where users don't deploy contracts themselves. The second group is reports just stating the users have different addresses on different chains, without any explanation as to why. If you have any questions, please ask.

**Comment by SovaSlava** [comment]
Include please my issue 456.
Yes, i didnt describe fully problem in issue, but i made escalation in my issue with normal description(where i tell about multisig contracts case - https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/456#:~:text=This%20multisig%20contract%20has  (link to comment)
And also there - https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#:~:text=even%20other%20situation%20%2D-,multisig%20contract,-%2C%20when%20user%20purchase (link to comment)

**Comment by 0xshivay** [comment]
Issue #476 accurately identifies the root cause with a correct explanation. I request the judge to consider this issue as a duplicate of Issue #122.

**Comment by 0xsimao** [comment]
@WangSecurity could you share where in the readme or code it is stated that aa wallets are supported? If there isn't any reference, this is user mistake, as you previously mentioned. It's not fair to validate out of scope issues.

**Comment by blckhv** [comment]
#166 is also dup, it mentions the usage of Gnosis safes and they also can have different addresses across chains

**Comment by gkrastenov** [comment]
I believe that this issue #594 is duplicate

**Comment by mcgrathcoutinho** [comment]
@WangSecurity I believe this issue https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/606 is also a duplicate.

**Comment by PeterSRWeb3** [comment]
I believe this is a duplicate also https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/321

**Comment by WangSecurity** [comment]
> could you share where in the readme or code it is stated that aa wallets are supported? 

AA wallets are quite a common use nowadays and they don't have to be explicitly mentioned in the README to be supported and we should treat them as in-scope by default.

About the user mistake, it's not the user's control which addresses their AA wallet has. Fair argument is that they can still a normal wallet to use, but it's not grounds to exclude the AA wallets out of scope, and (as said above) we should treat them as in-scope by default.

#456 -- it's invalid because it mentions the user using contracts to participate in the contest and it's their responsibility to verify if the contracts they deploy have the same address and it's in their control to make sure these addresses have the same address. Hence, it's invalid since involves the user mistake.
#312 -- it just states "it's likely the address is different on different chains" without any explanation why. Hence, it's not sufficient to be a valid duplicate.

The decision remains the same, accept the escalation and validate with medium severity, the duplication list have been updated.

**Comment by 0xsimao** [comment]
@WangSecurity users are responsible to ensure that their wallet is compatible with the protocol.

> About the user mistake, it's not the user's control which addresses their AA wallet has.

We should assume they act in their best interest and understand that the prize will be claimed on the same address on Ethereum. Users are also responsible to know how their wallet works and that the address may differ in the other network.

The loss is only on the user, it doesn't impact any other users.

This is a clear user mistake, regardless of aa accounts being common or not.

**Comment by 0xDenzi** [comment]
@WangSecurity #614 is also a duplicate.

**Comment by 0xshivay** [comment]
@WangSecurity #476 is also a duplicate.

**Comment by ke1caM** [comment]
https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/74 is also a duplicate

**Comment by cawfree** [comment]
Escalate

ERC-4337 requires [EIP-7562](https://eips.ethereum.org/EIPS/eip-7562), which asserts that AA solutions may only execute transactions that reference a handful of whitelisted opcodes which cannot lead to execution differences when the transaction is executed on chain.

If you check the EIP, AA `UserOperation`s **must not** include any of the following opcodes:

```
Opcode Rules
Block access from opcodes that access information outside of storage and code (aka “environment”).

[OP-011] Blocked opcodes:
ORIGIN (0x32)
GASPRICE (0x3A)
BLOCKHASH (0x40)
COINBASE (0x41)
TIMESTAMP (0x42)
NUMBER (0x43)
PREVRANDAO/DIFFICULTY (0x44)
GASLIMIT (0x45)
BASEFEE (0x48)
CREATE (0xF0)
INVALID (0xFE)
SELFDESTRUCT (0xFF)
```

Therefore, this issue **should only be considered valid specifically for findings which reference multisigs**, since it is actually impossible to interact using a compliant AA implementation as per the EIP, as purchasing a ticket [underlyingly depends on the `block.timestamp` opcode](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L409).

**Comment by kuprumxyz** [comment]
But both [EIP-4337](https://eips.ethereum.org/EIPS/eip-4337) and [EIP-7562](https://eips.ethereum.org/EIPS/eip-7562) are _drafts_, aren't they? Thus, I suppose, the judging can't be based on those?

> :warning: Draft
> This EIP is not yet recommended for general use or implementation, as it is subject to normative (breaking) changes.

**Comment by cawfree** [comment]
@kuprumxyz 

If an account abstraction wallet is cited as the reason for validity for this bug, then what other specification do we have to judge by?

**Comment by 0xHuntoor** [comment]
@WangSecurity hey wang, came through this issue since i saw it quoted on another contest

As per sherlock rules, EIP integrations should be stated explicitly in the readMe and have high/med impacts

Per my understanding: this issue has impact but the EIP is not explicitly stated?

Saying its quite common thing now a days doesn't allow to override the rules, till this day protocols still mention if they are going to explicitly integrate with EIPs (even when they are ERC20, ERC721 which are more common than AA), take a look at **`fLayer`** contest

**Comment by CarlosAlegreUr** [comment]
I have not read all the messages. I just want to point out that a smart contract, regardless of implementing an Account Abstraction, if a smart contract participates on a raffle and wins, the protocol will send the prize to that very same address on the other chain. Which might or might not be controlled by the owner of the smart contract in the raffle chain.

Account Abstraction is just a very specific kind of smart contract that is popular. But any contract that has code to participate in the raffles will create this issue if it wins.

**Comment by cawfree** [comment]
> I have not read all the messages. I just want to point out that a smart contract, regardless of implementing an Account Abstraction, if a smart contract participates on a raffle and wins, the protocol will send the prize to that very same address on the other chain. Which might or might not be controlled by the owner of the smart contract in the raffle chain.
> 
> Account Abstraction is just a very specific kind of smart contract that is popular. But any contract that has code to participate in the raffles will create this issue if it wins.

Okay, so watsons defending this issue contend that Account Abstraction is _both_ extremely popular and thus very likely to encounter real world consequences, whilst simultaneously lacking any of the real adoption or network effect as a protocol specification, since the reference is a kind of fluid standard which no-one can agree upon. 😅

Account Abstraction has a specific meaning - if we intend to use it to justify a finding, then we need to look at what that meaning is. These opcodes are blacklisted specifically for the security vulnerabilities of batching together arbitrary `UserOperation`s, so pick your AA flavoured poison, you are going to be exposed to the same vulnerabilities of users competing to land on-chain transactions that deviate from their simulated expectations.

The `block.timestamp` opcode is not supported by AA, so you can't enter the raffle.

**Comment by WangSecurity** [comment]
I see there's a question about EIP-4337 and EIP-7562 not being mentioned in the EIP question. The problem here is that the EIP question is about protocol contracts, i.e. if these EIPs are in this question, then the in-scope contracts should be EIP-4337 and EIP-7562, not the contracts that integrate with the protocol (i.e. AA wallets).

But there's a great comment from @cawfree that the AA wallets will not be able to use the protocol in the first place. Also, further considering comments and points from @0xsimao. Indeed, this is a user mistake cause users are aware upfront that the prize is sent on the other chain and it's their responsibility to verify if they have the same address on different chains. Moreover, it's possible to deploy and control contracts with the same address but on different chains.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by AtanasDimulski** [comment]
@WangSecurity how has missing functionality that results in a loss of funds become a user mistake?  As per this comment *@WangSecurity could you share where in the readme or code it is stated that aa wallets are supported? If there isn't any reference, this is user mistake, as you previously mentioned. It's not fair to validate out-of-scope issues.* The support of AA wallets is logical, it is possible, many issues have described how many AA wallets people are utilizing, and this number continues to grow. The readme doesn't specify that AA wallets won't be supported. This is not how the README works, the protocols are supposed to put in there everything that is a known risk beforehand. The second point that was made about the user having to know what would happen if he entered the raffle with AA wallet, so now we claim that each user of the Winnables protocol has to be an auditor, this is not serious. The main point why this issue is a valid med is that when it comes  to cross chain protocols they are supposed to provide the possibility of users to set the correct address on the receiving chain, this is clearly missing form here and you can't expect the user to "know that". It is fairly possible for users to use AA wallets - medium probability, impact is high - thus the issue can even be considered a valid high. Trying to spin this as a user mistake is not serious. I can provide links to such accepted high issues, I already have.

**Comment by kuprumxyz** [comment]
I think the discussion here revolves too much around AA wallets, which are not the only kind of smart wallets. The finding is broader, and is much better explicated e.g. by #157:

> Smart-wallet winners on Avalanche cannot claim their prizes on the mainnet due to smart-wallet address discrepancies between chains, rendering their winnings inaccessible.
> 1. Smart wallets, including multi-signature wallets and Account Abstraction wallets, are valid entities for purchasing tickets as they are explicitly supported by the WinnablesTicket::mint function
> 2. Once a winner is selected after the Chainlink VRF response, **the same winning address from Avalanche is propagated to the mainnet** _<=== the vulnerability_
> 3. However, if the winner is a smart wallet, its address on Avalanche will not be the same on the mainnet. This discrepancy means that smart-wallet winners cannot claim their prize on the mainnet, as the propagated address will not match their mainnet address.

So, the vulnerability is in these contracts, because they allow a smart contract to enter the raffle, but then mistakenly propagate the same address from Avalanche to Ethereum, thus making the prize inaccessible to the winner. Instead, the contracts on Avalanche should have the ability for the user to specify the claiming address on Ethereum.

_Disclaimer: I am a complete side party in this: my issues are not among the duplicates. If anything, I am arguing against my own interests, as accepting this finding will reduce my share from the other ones._

**Comment by WangSecurity** [comment]
@AtanasDimulski it's a fair claim, but here, the problem is not that users should know about this issue and shouldn't be using Winnables when they have different addresses on different chains.

The problem here is that the users should be aware that with AA wallets, they may not control the same address on different chains. This doesn't mean they have to be auditors, that's a very well-known behaviour of AA wallets and any user using AA wallets should be aware of this just by using their wallet. Again, I'm not saying they should be aware of the issues, I'm saying that they're aware of how their wallets work.

Moreover, deploying the AA wallets on different chains with the same address is possible. And, as @cawfree noticed correctly, AA wallets couldn't join a raffle in the first place.

@kuprumxyz the users can still deploy contracts with the same address on different chains. Moreover, I think it's quite intuitive that if you cannot choose the address to receive the prize on another chain, then it will be the same address you used to enter the raffle. I'm not saying this is the main and strong argument to invalidate this issue, just sharing my perspective.

To reiterate, I'm not saying the users should be aware of any of the issues or it's a known issue; I'm saying that users should be aware if they control the same address on different chains, and it doesn't require them to be auditors.

The decision remains, reject the escalation and leave the issue as it is.

**Comment by kuprumxyz** [comment]
@WangSecurity here is another, main argument to consider:

**_When entering a raffle, a smart wallet user is unaware that they won't be able to claim the prize._**

Here are the supporting references:

- The [Winnables page](https://testnet.winnables.com/):
  - A user only needs to _connect wallet_ to be able to buy tickets. At that point they are not aware that they need to possess the same address on Ethereum.
- The [Winnables docs:: How it works section](https://winnables.gitbook.io/home/how-it-works/raffles)
   > _To enter a raffle, participants need to purchase tickets. Each ticket serves as an entry into the draw. The more tickets a person has, the higher their chances of winning._
- The [Winnables docs::FAQ](https://winnables.gitbook.io/home/how-it-works/frequently-asked-questions):
  > _**How are the prizes transferred?**_
  > _Once the winner is determined by the Chainlink VRF system, he will need to click on the “claim” button on the competition page. Once claimed, the prize will be transferred to the winners connected wallet._


_Thus the system docs and the implementation mislead the user to believe that if they buy tickets (with whatever type of wallet) they will be able to claim the prize, which is not the case; this is a bug, and a loss of funds_.

To mitigate that, the system should do either of the following:
- Before allowing users to buy tickets, require them to either supply a prize withdraw address on Ethereum, or click a checkbox "I possess the same address on Ethereum"
- When claiming a prize, use the user wallet on Avalanche for claiming the prize on Ethereum, i.e. send a CCIP message with the Ethereum withdrawal address the user provides when claiming.

**Comment by WangSecurity** [comment]
@kuprumxyz, thank you for providing this documentation. But, unfortunately, this doesn't stand above the rules since the user could successfully participate in a raffle without losing funds if they control the same address on different chains. Moreover, the user who makes such a mistake (i.e. enters the raffle when they don't control the same address on different chains) is the only one who suffers a loss. 

In that sense, the issue's impact is to either show the discrepancy in the doc or allow using different addresses to enter the raffle and claim the prize. Hence, I still see it as low severity, the decision remains as it is, reject the escalation and leave the issue as it is.

**Comment by Brivan-26** [comment]
@WangSecurity There are some parts of your comment I don't understand.
First:
>  this doesn't stand above the rules since the user could successfully participate in a raffle without losing funds if they control the same address on different chains

This refers to the happy path only, not the unhappy path that this issue describes. So, I don't see what value this phrase added here

Second:
> Moreover, the user who makes such a **mistake** (i.e. enters the raffle when they don't control the same address on different chains) is the only one who suffers a loss.

I disagree that this is a user *mistake*. It is totally valid that a user using his smart wallet to interact with the protocol, and according to the current stats, abstracted wallets are increasingly being adopted. So, calling the user who uses his smart wallet to interact with a protocol a *mistake* is inappropriate.

Moreover, the documentations referenced by @kuprumxyz in [this comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2365058614) highlight that the user is expecting to get the rewards with the same address he used when he entered the raffle.

**Comment by Blngogo** [comment]
Woah, what a quick mind switch up, feel like the new judging system arrived here, one comment from watsons with higher authority and then boom - invalid. Hey @WangSecurity quoting you here when you initially agreed that its a Medium: " Even though the AA owner should know they have different addresses on different chains, this issue leads to AA wallets not being able to participate in Raffles. Planning to accept the escalation and validate with medium severity". Now with the same arguments you are stating that its a low severity? How come? The impact on this issue is clearly high. You are saying that to be able to successfully participate, users should be devs basically, that they must be aware of address differentation beforehand, then deploy same addresses on different chains. What about the other 99% of the contributors in DeFi, which are not devs? Missing functionality, which leads to loss of funds is not low severity even if its on the user side. Protocol only requires from users to connect wallet to participate, no one awarns you for such scenario. There are watsons here coming with valid arguments, proving the validity of the issue and trying to cover up by only saying "users should be aware, it's a user mistake" is a little unproffesional for a LJ. 

Also don't understand why sponsors disputed on this one and won't fix it. Quite simple fix. If we take this issue, as real-world example, simply as a regular user you will participate with your aa wallet, then lose your funds. Who would continue to interact with this project? No one would think: "well for next time i will know".

**Comment by iamnmt** [comment]
If there is a path that a user can take to use the functionality without causing any loss to themselves, then the user is expected to take that path. If the user does not take that path, which in turn will cause loss to themselves, then it is a user mistake. This is how a user mistake issue is judged.

**Comment by kuprumxyz** [comment]
That part, about _"user mistake"_ and _"If there is a path that a user can take to use the functionality without causing any loss to themselves, then the user is expected to take that path"_ I would like to understand better. Could someone please point me to the relevant Sherlock docs? The only thing I could find about user mistakes is in [List of Issue categories that are not considered valid](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid):

> _**User input validation**: User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high._

But the citation above is clearly not applicable to this issue, right? The user doesn't  provide an erroneous address on Ethereum which they don't control as input; they only participate in a raffle as anyone else. _The signing address which the user employs to submit a transaction is not the function input._  The signing address is the inseparable part of user identity, and not something which they provide as input. There is simply no such thing as _invalid signing address_.

The signature of function [buyTickets](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L177-L187) witnesses this:

```solidity
    /// @notice (Public) Participate in a raffle
    /// @param raffleId ID of the Raffle
    /// @param ticketCount Number of tickets purchased
    /// @param blockNumber Number of the block when the signature expires
    /// @param signature Signature provided by the API to authorize this ticket sale at given price
    function buyTickets(
        uint256 raffleId,
        uint16 ticketCount,
        uint256 blockNumber,
        bytes calldata signature
    ) external payable {
```

Then what part of the docs the judging is based on?

**Comment by WangSecurity** [comment]
Watsons, refrain from comments that do not add any value to the discussion (e.g. "the decision changed because of a reputable watson commenting").

Knowing that your contracts have different addresses on different chains doesn't require you to be a dev. The user can deploy a smart contract wallet themselves and get the same address. They also can use smart wallet applications and deploy the wallets on different chains with the same address.

Again, about the docs. Firstly, they don't stand above the rules. Secondly, they're not complete; you can see the FAQ contains several empty sections, for example. Thirdly, even if you want to use it as an argument the users won't be aware the protocol is deployed on different chains, at the top of the [main page](https://testnet.winnables.com/) it says Join via Avalance and claim Ethereum Network prizes. 

Regarding the user mistake, the rule quoted above is indeed about input validation, and of course, the address we signed the transaction with is not an input. Still, the protocol doesn't allow using different addresses for entering the raffle and receiving the prize, so it's the user's responsibility to check if they control the same address on different chains. 

Moreover, the issue doesn't come from the protocol not functioning correctly and can be mitigated by the users themselves.

That's why my decision remains the same, reject the escalation and leave the issue as it is.

**Comment by Blngogo** [comment]
@WangSecurity Sir, about what rule we are talking about here: "Again, about the docs. Firstly, they don't stand above the rules"? Based on what rule this issue is judged? This issue is not judged based on any rule that's why docs are mentioned. The protocol requires from users only to connect a wallet, if we follow your sayings, there must be few preconditions that users must do in order to successfully claim their prize. If that's the case, which project will not mention it in their documentation? Such issue on every other platform is considered as High.

And i don't quite get, what do you mean by this: "Secondly, they're not complete; you can see the FAQ contains several empty sections, for example". You think that the preconditions for users will be added? Even if they are added, we are auditing the given codebase and following the given docs, where this part is currently missing. To me this seems very insufficient argument.

 And for your third argument, as you said the main page says, Join via Avalanche, claim on Mainnet but if you do it, you won't be able to claim actually, and this is what other watsons are saying so. In order to successfully claim, you must do some preconditions. 
 
 "Still, the protocol doesn't allow using different addresses for entering the raffle and receiving the prize, so it's the user's responsibility to check if they control the same address on different chains." - The missing fix for the issue, can't fall down on users shoulder and considered as user mistake. Based on this statement almost every issue can be considered as user mistake.

**Comment by kuprumxyz** [comment]
@WangSecurity thank you for the explanation. For everyone's sake, I will try to algorithmize it:

> Again, about the docs. Firstly, they don't stand above the rules. Secondly, they're not complete; you can see the FAQ contains several empty sections, for example. Thirdly, even if you want to use it as an argument the users won't be aware the protocol is deployed on different chains, at the top of the [main page](https://testnet.winnables.com/) it says Join via Avalance and claim Ethereum Network prizes.

1. Per [Hierarchy of truth](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging/README.md#iii-sherlocks-standards), we have
   > If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth.
  
    Interpretation: the protocol docs don't mention that the user will need to possess the same address on Ethereum, but the docs are not in the Hierarchy of truth, so they are irrelevant. The [README](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/README.md#q-on-what-chains-are-the-smart-contracts-going-to-be-deployed) does say that the WinnablePrizeManager will be deployed on Ethereum. Thus we have to treat this as the guiding information; not what's in the docs.

> Regarding the user mistake, the rule quoted above is indeed about input validation, and of course, the address we signed the transaction with is not an input. Still, the protocol doesn't allow using different addresses for entering the raffle and receiving the prize, so it's the user's responsibility to check if they control the same address on different chains.

2. From p.1 we have to assume that the above information from the README (_"WinnablePrizeManager will be deployed on Ethereum"_) is also available to the user. Thus _it may be regarded as a user mistake_ to employ the address which has no counterpart on Ethereum.

> Moreover, the issue doesn't come from the protocol not functioning correctly and can be mitigated by the users themselves.

3. The issue doesn't indeed _necessarily_ require fixing the protocol. It may function _as is_, and the issue can be mitigated by either:
   - The user employing an address which they also possess on Ethereum
   - The protocol fixing the docs, and adding the sentence _"Users entering a raffle are required to possess the same address on Etehreum to be able to claim the prize"_.

From my side, though I don't necessarily agree with the above mitigations, but I see the point in that it may be a _design decision_ of the protocol to leave the implementation _as is_.

**Comment by WangSecurity** [comment]
> Sir, about what rule we are talking about here: "Again, about the docs. Firstly, they don't stand above the rules"? Based on what rule this issue is judged? This issue is not judged based on any rule that's why docs are mentioned. The protocol requires from users only to connect a wallet, if we follow your sayings, there must be few preconditions that users must do in order to successfully claim their prize. If that's the case, which project will not mention it in their documentation? Such issue on every other platform is considered as High.

As I've said the protocol's documentation is not a source of truth and cannot be used as an argument to validate the finding.

> And i don't quite get, what do you mean by this: "Secondly, they're not complete; you can see the FAQ contains several empty sections, for example". You think that the preconditions for users will be added? Even if they are added, we are auditing the given codebase and following the given docs, where this part is currently missing. To me this seems very insufficient argument.

I don't mean they will be added, I mean the second reason to not use docs as an argument (after that not being a source of truth) is because they are not complete. 

> And for your third argument, as you said the main page says, Join via Avalanche, claim on Mainnet but if you do it, you won't be able to claim actually, and this is what other watsons are saying so. In order to successfully claim, you must do some preconditions.

Excuse me for the confusion, with that I meant to say that the user will know the protocol function over 2 chains and you'll have to claim the prize on another chain if you win. But, it's only a counterargument to the argument of Winnables docs not mentioning 2 different chains. Still, any of the arguments referring to the Winnables site or docs are not grounds to validate the issue.

> "Still, the protocol doesn't allow using different addresses for entering the raffle and receiving the prize, so it's the user's responsibility to check if they control the same address on different chains." - The missing fix for the issue, can't fall down on users shoulder and considered as user mistake. Based on this statement almost every issue can be considered as user mistake.

No, not "almost every issue can be considered as user mistake", here it's clear the user can successfully use the protocol without a loss.

Hence, the decision remains, reject the escalation and leave the issue as it is.

**Comment by Blngogo** [comment]
@WangSecurity also please, check this [comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2365492751), would like to hear your counterarguments to invalidate the issue on this one.

**Comment by kuprumxyz** [comment]
> @WangSecurity also please, check this [comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2365492751), would like to hear your counterarguments to invalidate the issue on this one.

@Blngogo in fact @WangSecurity already [answered](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2367000738) the comment of mine you are referring to, and I have slightly [restructured](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122#issuecomment-2367385025) their reply in my subsequent comment.

As to myself, I now feel convinced by the provided arguments. The main argument from my point of view is that this issue can be mitigated _by fixing the docs_, and leaving the code untouched.

**Comment by Blngogo** [comment]
@kuprumxyz if it goes by fixing the docs, user must still do some preconditions. As the fix suggests, which is allowing the winner to choose a destination address, seems much more appropriate to me. After all we are reviewing the code, based on this code simply by connecting wallet, you can't claim your prize. I don't know what are these preconditions that user must do, before interacting with a DeFi project. As an ex-DeFi contributor (utilized the services of many DeFi projects, also worked in some), i have never encountered doing such things to pull your prize, i mean by yourself predict that your address will be different, deploy contracts to match addresses, etc... Thats not what a protocol should require from its users, not to mention that there is no way to withdraw them, so if a winner fails to claim the funds will be locked. Same issue was High on CodeHawks, and sponsors agreed with no hesitation and the project is not unknown one at all, here is some carnage, doesn't even make it to Low. Impact here is loss of funds, so what if no user does the preconditions, that means all the funds will stay locked and sponsors are ok with it? The pot is 8k in anyway, this is not about getting this issue validated and get extra 5$. Just it has high impact.

**Comment by kuprumxyz** [comment]
> @kuprumxyz if it goes by fixing the docs, user must still do some preconditions. As the fix suggests, which is allowing the winner to choose a destination address, seems much more appropriate to me.

@Blngogo with that I completely agree: this is how the project code _should be implemented_. I am also a developer and a QA person in the past, btw, so yes, I do agree.

The point is, we are in a different setup here. We are not developers who advise their fellow developers how they should structure their code. We are auditors who check the code, and find vulnerabilities which are classified _according to the platform rules_. And yes, the rules at CodeHawks may be different. But we are at Sherlock, so we have to follow Sherlock rules. In the discussion above we've elaborated why this is Low severity according to Sherlock rules.

I feel your pain, but rules are rules. In all honesty, I prefer to follow the rules (though I of course wish them to be more precisely formulated) and to be able to discuss with the community and the HoJ why a particular decision is made, than to be at the complete mercy of a randomly selected judge at another platform.

**Comment by Oblivionis214** [comment]
Agree this is invalid. Users should aware rewards are only on Ethereum.
![image](https://github.com/user-attachments/assets/65076c41-60ce-4cc3-9fb0-9208a5e9eb26)

**Comment by WangSecurity** [comment]
The decision remains. As I've said before, it's the user's responsibility to see if they can claim the prize on the same address on a different chains. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [CarlosAlegreUr](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/122/#issuecomment-2329301910): rejected
