### ISSUE TITLE
neko_nyaa - Hardcoded `extraArgs` in CCIP message send

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-winnables-raffles-judging#131]
neko_nyaa

Medium

# Hardcoded `extraArgs` in CCIP message send

### Summary

Hardcoded `extraArgs` may brick CCIP message sending in CCIP upgrades.

### Root Cause

Per the Chainlink docs:

> Do not hardcode `extraArgs`: To simplify the example, `extraArgs` are hardcoded in the contract. The recommendation is to make sure `extraArgs` is mutable. For example, you can build `extraArgs` offchain and pass it in your functions call or store it in a storage variable that you can update on demand. Thus, you can make sure `extraArgs` remains backward compatible for future CCIP upgrades.

In `BaseCCIPSender`, `extraArgs` is hardcoded when sendings messages:

```solidity
Client.EVM2AnyMessage memory message = Client.EVM2AnyMessage({
    receiver: abi.encode(ccipDestAddress),
    data: data,
    tokenAmounts: new Client.EVMTokenAmount[](0),
    extraArgs: "", // @audits hardcoded
    feeToken: LINK_TOKEN
});
```

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/BaseCCIPSender.sol#L32

### Impact

Throughout the codebase, multiple functionalities use CCIP send:
- When locking prizes for a raffle: https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesPrizeManager.sol#L163
- When cancelling a raffle: https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L282
- When propagating the winner to Mainnet: https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L340

CCIP upgrades may brick the protocol altogether. This was warned in the Chainlink docs **as of currently**.

### Mitigation

`extraArgs` should be mutable and settable by the admin.

**Comment by neko-nyaa** [comment]
Escalate. If #236 is valid, then this is also valid, since they both show a scenario in which Chainlink can brick CCIP messages. Furthermore, this info is mentioned [in the **current** Chainlink docs](https://docs.chain.link/ccip/best-practices#using-extraargs).

As mentioned in the impact section, multiple functionalities will be bricked altogether. I don't think "cancelling a raffle can be bricked" needs to be explicitly mentioned in the report, as it was [clear in the code](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L212) that only a cancelled raffle can be refunded, so bricking cancelling should also automatically lead to non-refundable funds.

**Comment by Brivan-26** [comment]
There is no issue here and this issue does not seem a dup of #236 .
The `extraArgs` specifies the `gasLimit` for relaying the message to the recipient contract on the destination blockchain. There is no need to set it because the contract only transfers tokens and does not expect function calls on the destination blockchain.

**Comment by 0xarshia** [comment]
Yes the esclation neko made seems correct and Valid 

thanks, brivian for your comment but respectfully i disagree

as he does not say it should be dup of any issue but he says the "both show a scenario in which Chainlink can brick CCIP messages." which is different 

about the validity of issue the chainlink clearly specified in their documentation that this param should NEVER be hardcoded 

![image](https://github.com/user-attachments/assets/b0d52165-fa02-4fcd-93b8-a444ffd34b78)

and also sponsor agrees on the issue as he confirmed the issue and will work on it to fix it.  
 
![image](https://github.com/user-attachments/assets/06de277b-2f91-4fb8-ac86-81bf088c03bd)

The careful sponsor noticed the issue and he was shocked that someone from the Chainlink team told them there would be no changes ( docs said otherwise) and to make the CCIP Router immutable then he found out that this issue existed

yes sponsor opinion on Sherlock platform might be not the real proof behind the validity of the issue 


however, we can see in here that Chainlink clearly stated this fact in their doc and also if protocol is using external libraries and protocols they always usually consider security considerations as we saw many times the issue poped out when protocols weren't following the security considerations 

i think the issue is pretty valid and as the impacts the of issue both 236 and this "both show a scenario in which Chainlink can brick CCIP messages." 

https://docs.chain.link/ccip/best-practices#using-extraargs

**Comment by Brivan-26** [comment]
@0xarshia Read the full chainlink's warrant. You need to make `extraArgs` mutable **when you pass a function call in the message or store it in a variable that you want to update on-demand later**.
This is irrelevant in this protocol, the protocol is **there is no function call being sent in the message, and this message will not change**

For future chainlink upgrade's compatibility. This is Out of scope per contest README

**Comment by mystery0x** [comment]
While extraArgs should be admin-provided and loaded from storage, this finding could at best be low as far as gas optimizations will be of concern.

Additionally, anything that is related to future integrations will be OOS as per contest readme.

**Comment by imp0wd3r** [comment]
The biggest issue with hardcoded extraArgs right now is that too much gas is paid, and I submitted this bug https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/203, which has nothing to do with future changes.

**Comment by Oblivionis214** [comment]
Actually CCIP 1.0 1.2 1.5 share the same `extraArgs`. There is no evidence the ABI may/should change in the future. It is a best-practice to make this mutable, but the issue itself has no actual impact.
> VII. List of Issue categories that are not considered valid:
> Gas optimizations: The user/protocol ends up paying a little extra gas because of this issue.

**Comment by WangSecurity** [comment]
Firstly, this is only a recommendation to not hardcode `extraArgs` as it may brick the protocol in the **future upgrades**, i.e. currently, there's no issue and can only happen in case of implementation upgrades, which is invalid:
> Future issues: Issues that result out of a future integration/implementation that was not mentioned in the docs/README or because of a future change in the code (as a fix to another issue) are not valid issues

Secondly, as correctly explained in [this comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/131#issuecomment-2329629407), this warrant has nothing to do with how Winnables use CCIP.

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [neko-nyaa](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/131/#issuecomment-2329402152): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/15
