### ISSUE TITLE
aslanbek - Legitimate users who called `buyTickets` at the last second of the raffle may not be able to participate

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#208]
aslanbek

Medium

# Legitimate users who called `buyTickets` at the last second of the raffle may not be able to participate

### Summary

Because it is possible to `cancelRaffle` / `drawWinner` at `raffle.endsAt`, legitimate users may not be able to participate in the raffle if they call `buyTickets` at the last second.

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L422-L441

### Root Cause

`_checkShouldDraw` / `_checkShouldCancel` do not revert at `raffle.endsAt`.

### Internal pre-conditions

`block.timestamp == raffle.endsAt`
`currentTicketSold < raffle.maxTicketSupply`

### External pre-conditions

At `t = raffle.endsAt`, any user calls `drawWinner` (if enough tickets were sold), or `cancelRaffle` (if not enough tickets were sold).

### Impact

Users who call `buyTickets` at the last second of the raffle will not be able to participate if the raffle was cancelled / winner was drawn earlier in the same block.

### Mitigation

```diff
    function _checkShouldCancel(uint256 raffleId) internal view {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status == RaffleStatus.PRIZE_LOCKED) return;
        if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle();
-       if (raffle.endsAt > block.timestamp) revert RaffleIsStillOpen();
+       if (raffle.endsAt >= block.timestamp) revert RaffleIsStillOpen();
        uint256 supply = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
        if (supply > raffle.minTicketsThreshold) revert TargetTicketsReached();
    }
```

```diff
    function _checkShouldDraw(uint256 raffleId) internal view {
        Raffle storage raffle = _raffles[raffleId];
        if (raffle.status != RaffleStatus.IDLE) revert InvalidRaffle();
        uint256 currentTicketSold = IWinnablesTicket(TICKETS_CONTRACT).supplyOf(raffleId);
        if (currentTicketSold == 0) revert NoParticipants();
-       if (block.timestamp < raffle.endsAt) {
+       if (block.timestamp <= raffle.endsAt) {
            if (currentTicketSold < raffle.maxTicketSupply) revert RaffleIsStillOpen();
        }
        if (currentTicketSold < raffle.minTicketsThreshold) revert TargetTicketsNotReached();
    }
```

**Comment by aslanbekaibimov** [comment]
Escalate

Anyone can prevent valid `buyTickets` transactions in the last second of the raffle. If not fixed, this allows the following scenarios:

1. Attacker-participant A increases his chance of winning by calling `drawWinner` at the last second of the raffle, blocking all last-second participants. Protocol misses out on revenue from these tickets.

2. Attacker-participant B does not want to participate anymore in a raffle that has `currentTicketSold <= minTicketsThreshold` by the start of the last second of the raffle. Even if `minTicketsThreshold` is going to be reached due to last-block purchases, he guarantees the cancellation by buying `minTicketsThreshold - currentTicketSold` tickets and calling `cancelRaffle`. For each user who spent less on tickets than their expected prize, the attack would nullify their positive EV.

3. Same as in (2), any user who did not participate can grief the raffle that would have enough tickets in the [intended timeframe](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L248-L249), wasting admin's and participants' time.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Anyone can prevent valid `buyTickets` transactions in the last second of the raffle. If not fixed, this allows the following scenarios:
> 
> 1. Attacker-participant A increases his chance of winning by calling `drawWinner` at the last second of the raffle, blocking all last-second participants. Protocol misses out on revenue from these tickets.
> 
> 2. Attacker-participant B does not want to participate anymore in a raffle that has `currentTicketSold <= minTicketsThreshold` by the start of the last second of the raffle. Even if `minTicketsThreshold` is going to be reached due to last-block purchases, he guarantees the cancellation by buying `minTicketsThreshold - currentTicketSold` tickets and calling `cancelRaffle`. For each user who spent less on tickets than their expected prize, the attack would nullify their positive EV.
> 
> 3. Same as in (2), any user who did not participate can grief the raffle that would have enough tickets in the [intended timeframe](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L248-L249), wasting admin's and participants' time.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
A fixed is desired to perfect the conditional check but it's deemed low given the trivial change needed.

**Comment by dinkrass** [comment]
Dup of [611]( https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/611)

> A fixed is desired to perfect the conditional check but it's deemed low given the trivial change needed.

[mystery0x](https://github.com/mystery0x)
I've never seen such Sherlock requirement: easy fix -> low severity. Could you provide the docs for that?

### Why this attack is possible to happen?
- Due to network congestion, users or bots, looking for opportunities to bid as late as possible could bid at the last second of a raffle( which does not meet the min tickets requirement yet). They are incentivized to do that in order to calculate their chance of winning as late as possible and if the chance is big enough to bid at the last second, with a ticket count that satisfies the min ticket number of a valid raffle.

### Impact. Who loses what?
- The protocol loses all deposited AVAX for a valid raffle. 
  - Normal scenario(without the attack):
		 The raffle will meet the min tickets requirement at the last second, refunds will not be possible and the protocol will keep all AVAX deposited by the bidders.
  - Attack scenario
		However, an attacker frontrunning those last second bids, that make the raffle meet it's min tickets requirement, will force the protocol to return all deposited AVAX to the bidders -> loss of AVAX for the protocol. In order to do that the attacker will execute: `WinnablesTicketManager::cancelRaffle()`
-  the future raffle winner loses his reward


Also, there is a[ fix done by the dev team](https://github.com/Winnables/public-contracts/pull/10), which proves that the issue is real.

The reported issue meets the Sherlock's Medium requirements:
- Causes a loss of funds but requires certain external conditions or specific states, or a loss is highly constrained. The losses must exceed small, finite amount of funds, and any amount relevant based on the precision or significance of the loss.

**Comment by rbserver** [comment]
#341 is also a dup of this.

**Comment by blckhv** [comment]
#239 is dup as well

**Comment by WangSecurity** [comment]
To clarify, the root cause of this issue is that you can enter, cancel and draw a raffle at the same time at `raffle.endsAt` correct? (I understand it can be a silly clarification, still want to confirm I understand) and the impact is that you should be able to enter a raffle, but you cannot if the call to cancel the raffle or draw a winner has been made in the very same block?

**Comment by dinkrass** [comment]
Also on the impact
If the raffle gets canceled at the last second(considering it will meet the min tickets number at the last second, but the `buyTickets()` txs got frontrunned by a `cancelRaffle()` tx), the protocol has to refund all deposited AVAX for that raffle to the bidders and there will be no winner. Even though the conditions for a valid raffle could be satisfied with the last second buy ticket bids)

**Comment by WangSecurity** [comment]
After additionally considering this issue, indeed the user should be able to buy at this point and the raffle shouldn't be cancelled/drawn. Therefore, I believe it's a broken functionality preventing users from participating:
> Breaks core contract functionality, rendering the contract useless or leading to loss of funds.

Planning to accept the escalation and validate with medium severity. I will make this issue the main one. The duplicates are:
- #239 
- #341 (even though it has 3 scenarios and the ones about cancelling the raffle or drawing a winner before max ticket supply is reached are invalid, it still explains the issue from this report).
- #611 

> *Note: if there are any missing duplicates, please let me know.*

**Comment by 0xsimao** [comment]
@WangSecurity this issue is invalid.
If the round is drawn/cancelled before the user claims at the block which `block.timestamp == raffle.endsAt`, the transaction will [revert](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/81b28633d0f450e33a8b32976e17122418f5d47e/public-contracts/contracts/WinnablesTicketManager.sol#L410) as the status is no longer `IDLE`.
It works as expected.

There is nothing wrong with the round being able to buy tickets at `raffle.endsAt` and draw/cancel at the same time. The same as there is nothing [wrong](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/26) with the round being drawable/cancellable when the number of tickets is exactly `minTicketsSold`.

Both these issues are inflating the impact of a design choice. There is no loss, no DoS and nothing is broken.

**Comment by dinkrass** [comment]
> There is nothing wrong with the round being able to buy tickets at raffle.endsAt and draw/cancel at the same time.

> Both these issues are inflating the impact of a design choice. There is no loss, no DoS and nothing is broken.

@0xsimao 
The Winnables team does not think that way, they've already fixed this issue. Which proves it's not a design choice and an actual issue.

https://github.com/Winnables/public-contracts/pull/10/files#diff-0adad0474d3ab552e0ccee1196e2479225a8fe775321a52ec4c6c5a121d55351R447-R449

**Comment by 0xsimao** [comment]
@dinkrass there is still nothing wrong with the past design, they prefer the code this way but does not mean the code as was in the past lead to impacts worthy of medium severity.

**Comment by WangSecurity** [comment]
The part that is not the design here is that the users shouldn't be able to enter, cancel and draw the raffle when `block.timestamp == raffle.endsAt`. But, after considering this issue more, I'm going to revert my decision. Yes, this issue allows to draw and cancel the raffle 1s earlier than they should. But, it's only 1s and the users have lots of time before it to enter the raffle, hence, I agree that the impact is not sufficient for medium severity. Of course, anyone is free to elaborate on why this impact is significant enough for medium. But, for now, my decision is to reject the escalation and leave the issue as it is.

**Comment by aslanbekaibimov** [comment]
@WangSecurity  

Your previous decision was based on the broken functionality rule. What rule your current decision is based on?

**Comment by dinkrass** [comment]
@WangSecurity

> But, it's only 1s and the users have lots of time before it to enter the raffle, hence, I agree that the impact is not sufficient for medium severity

In case the raffle's reward value is low(during the raffle duration), the users are not incentivized to `buyTickets()`.
However, consider a scenario where near the end of a raffle, the value of the raffle reward increases significantly.
Example:  ERC20 reward that has avg USD value during ****almost** all** of the raffle period: 10USD. ERC20 reward value becomes 25 USD  **near the end** of a raffle.

Now the players are incentivezed to `buyTickets()` near the end of the raffle, because of the oppurtunity. 
The chance of a `buyTickets()` tx to be in the last second increases in case of a network congestion or bots looking to optimize their winning as late as possible. Bidding as late as possible provides them the most accurate value of their chance of winning, so they can decide how much to bid and if it's even worth it to bid or not.


This issue and [26 ](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/26) are similar. Could you elaborate why only [26 ](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/26) breaks core contract functionality and now this issue doesn't?

Thx for your time

**Comment by 0xsimao** [comment]
@dinkrass that is not relevant because the price may go in the other direction. The main point is 3 second diff is not worthy of medium severity.

**Comment by WangSecurity** [comment]
> Your previous decision was based on the broken functionality rule. What rule your current decision is based on?

@aslanbekaibimov That is a fair question. I still see it as broken functionality, but it does not render the contract useless since the users can still enter the raffle, just not in the last block.

@dinkrass, your comment is very interesting, thank you for providing this scenario. Still, as said above, the users can deposit at any time before this and successfully participate in the raffle. Hence, I still agree that it breaks the contract functionality but doesn't render the contract useless, and the users can still participate in the raffle. The decision remains, reject the escalation and leave the issue as it is.

**Comment by 0xHuntoor** [comment]
@WangSecurity 
As i understand, not every medium should render the contract useless?

I see `,` and `or` which means that all three definitions are valid medium?

**Comment by kuprumxyz** [comment]
As there are some parallels being drawn between this finding and finding #26, I think it makes sense to understand the similarities and differences _in numbers_.

### Probabilities

- Finding #26
  - _it's a vulnerability to cancel a raffle if `tickets == minTicketsThreshold`_
  - Typical number of tickets: 100 -- 60000
  - Typical minimal number of tickets: `0` -- `3000`; let's take `1000` 
- This finding:
  - _it's a vulnerability not to allow to buy a ticket if `block.timestamp == raffle.endsAt`_
  - Typical raffle duration: 1 week -- 1 month, i.e. `600_000` -- `2_500_000` seconds; let's take `1_000_000` seconds.

That alone tells us that #26 is at least `1000` times more probable to happen than this one.

Another aspect is _discrete_ vs _continuous_: 
- The number of tickets bought is _discrete_. As long as the number reaches minimum, a separate _discrete event_ is required to change that: that someone buys more tickets.
- The `block.timestamp` at which the transaction happens, on the contrary, can be considered _continuous_: it can be any second in a certain interval. Moreover, it's _unpredictable_, and depends on network congestion, the validator load, and a multitude of other factors. Thus, the probability of this finding wrt. 26 is even smaller than `1 / 1000`.

### Guarantees

- In finding 26, it is the main system guarantee that is broken (from the [README](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/README.md#q-please-list-any-known-issues-and-explicitly-state-the-acceptable-risks-for-each-known-issue)): 
  > _participants can be sure that by purchasing tickets, they have a hard minimum odds of winning equal to numberOfTicketsPuchased / totalTicketSupply_
- In this finding, what's broken is completely different, and can be formulated roughly as follows:
  - _A `buyTickets` transaction should succeed provided that all conditions are met; in that case the user will obtain the requested tickets_

Notice the different kind of guarantee in the latter case: it's a _soft, conditional guarantee_, which is provided under the premise that everything goes well with the transaction. _A user who submits a transaction at the last seconds of the raffle in no way may pretend to have a guarantee that their transaction will succeed_. They are effectively gambling: not only against other participants (which is the purpose of the system), but against other external factors: will their transaction make it in the next block? What is the network congestion now? Won't it be too late?

Thus, while in the former case the main system guarantee is broken, in the latter case the conditional guarantee has not been fulfilled due to the conditions involved. _It is a user mistake to try participating in a raffle at the last second_.

### Impacts

- In finding 26, the impact is:
  - _All users (say 100) participating in the raffle have their stakes at winning the raffle, all their funds frozen in a raffle for at least a week, being frozen in vein: they are deprived of right to may be win the prize._
- In this finding, the impact is:
  - _A single user doesn't succeed in buying tickets. No funds are frozen, system works as expected, but a user simply was too late to buy a ticket._

We can see that while the former is a valid Medium/High severity impact, the latter impact is Low/QA.

**Comment by WangSecurity** [comment]
> As i understand, not every medium should render the contract useless?

That's a very good question and the problem is how the following line is phrased:
> Breaks core contract functionality, rendering the contract useless or leading to loss of funds.

It means breaking core contract functionality, which renders the contract useless or leads to a loss of funds. I understand how this line is confusing in this sense, excuse me for not fixing it yet.

@kuprumxyz I don't have anything to add, it's a very great explanation. Though the probability is not considered when defining the severity, it's a very good explanation of why #26 may seem similar, but it doesn't make this issue medium severity. Really appreciate this great comment.

The decision remains the same, reject the escalation and leave the issue as it is.

**Comment by aslanbekaibimov** [comment]
I believe the main impact is that this allows any user to determine the final number of tickets for the raffle, in the same transaction where they purchase tickets.

E.g. Alice at the last second of each* raffle checks if buying tickets is positive EV for her, and if it is, she will `buyTickets` + `drawWinner` in the one transaction.

So essentially all* raffles where the prize is bigger than the value of tickets before the last second, will be "MEVed" by users like Alice.

**All/each where `raffle.endsAt` lands on a block's timestamp.*

**Comment by 0xHuntoor** [comment]
@WangSecurity do i understand it correctly that medium is now only a DOS or Loss of funds

**Comment by dinkrass** [comment]
The minimum duration for a raffle is defined as **60 seconds** in the code. In case of such short lived raffles, the probability of such last second attacks/issues increases significantly (1/60 in case of only short lived raffles).

```
uint256 constant internal MIN_RAFFLE_DURATION = 60;
...
    function _checkRaffleTimings(uint64 startsAt, uint64 endsAt) internal view {
        if (startsAt < block.timestamp) startsAt = uint64(block.timestamp);
        if (startsAt + MIN_RAFFLE_DURATION > endsAt) revert RaffleClosingTooSoon();
    }
```

https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L21
https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L401


However the judge has the final word and his final decision will be respected from my side.

**Comment by kuprumxyz** [comment]
Wang is right, and ultimately the probability is not that important. It does play a role, but not crucial. What's much more important is that _**it's a user mistake to try to participate in the raffle at the last second**_.

First of all, even the title of this finding, "_users who called buyTickets at the last second_" is misleading. We are not in a procedural setting where you may _call_ a procedure with precise timing. You _submit a transaction_, which goes over the mempool, gets broadcast, selected by validators, included into the final block, the timestamp for the block is selected, etc. A user who submits a transaction very close to the raffle end is gambling against all this external factors, though they should not. And if one of those factors didn't work in their favor, they have no right to complain.

I like analogies:) Here is one: If you are a driver approaching the traffic light, which turns :yellow_circle: , and you make a decision to drive regardless, you are making a mistake: :yellow_circle: prohibits driving. You may get lucky, or may not, and a tram or a too-fast driver from the crossing direction smashes into you.

Here is another: If you, as a Watson, submit a finding in the last seconds before the contest end, you are making a mistake. You may get lucky, and the Github works as it should, the bot processes your repo among the last, etc. Or you may not: the Github is slow to commit your finding, the bot processes your repo first, etc. If you are unlucky, and your finding doesn't find its way to the findings repo, you have no right to complain. It's your mistake, and you had all the contest duration to submit it.

**Comment by WangSecurity** [comment]
> I believe the main impact is that this allows any user to determine the final number of tickets for the raffle, in the same transaction where they purchase tickets.

It's a very good argument, but it still doesn't necessarily lead to a loss of funds or renders the contract useless (to some extent). That's why I don't see it as an issue, but rather a strategy/trade-off in the current state of the code.

> do i understand it correctly that medium is now only a DOS or Loss of funds

No, "rendered useless" doesn't mean it's DOSed but rather possesses large non-material damage so the system can't work the way it's intended. "Rendered useless" depends on how significant this non-material is based on the context of the codebase.

> The minimum duration for a raffle is defined as 60 seconds in the code. In case of such short lived raffles, the probability of such last second attacks/issues increases significantly

Still, there's no guarantee such an attack can happen, and I think the constraints/impacts remain the same as with any long-term raffle.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [aslanbekaibimov](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/208/#issuecomment-2329555769): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/10
