### ISSUE TITLE
charles__cheerful - Broken invariant, admin can stop winner from claiming prize

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-winnables-raffles-judging#286]
charles__cheerful

Medium

# Broken invariant, admin can stop winner from claiming prize

### Summary

For a winner to claim its prize a cross-chain tx has to be done from Avalanche to Ethereum. This transaction requires LINK token in the contract to get paid. The admin can just withdraw LINK token with `withdrawTokens()` from the `WinnablesTicketManager` contract and avoid the winner from claiming its prize.

As it's stated in the contest readme, `The principles that must always remain true are: -Winnables admins cannot do anything to prevent a winner from withdrawing their prize`. See [here](https://github.com/sherlock-audit/2024-08-winnables-raffles?tab=readme-ov-file#q-please-discuss-any-design-choices-you-made).

### Root Cause

Admin can withdraw any amount of LINK token from the contract in Avalanche network without any restrictions.

### Internal pre-conditions

Does not apply.

### External pre-conditions

Does not apply.

### Attack Path

1. Winner is chosen an `propagateRaffleWinner()` is called.
2. Admin sees this and front-runs this transaction with `withdrawTokens()` to withdraw enough LINK token from the contract so as to not have enough to pay for CCIP fees.

### Impact

Broken, as per devs words: **a principle that must always remain true**.

### PoC

The protocol assumes any token in `WinnablesTicketManager` is an accidentally sent token that is why there is no special checks to prevent any token withdrawal, see [here](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292). Yet the LINK token it is not accidentally sent, it is a token that is used to pay for the cross-chain transaction fees and it can be used for admin abuse to the winner.

Notice that the winner can always send LINK himself to the contract so there is enough. But really that does not matter as long as admin front-runs it can withdraw enough LINK to make the tx fail.

### Mitigation

If the token being withdrawn is LINK, force the contract to have a minimum balance of LINK, if admin tries to withdraw more than that, revert the withdrawal.

```diff
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress); 
        uint256 balance = token.balanceOf(address(this));
+       if(tokenAddress == LINK_ADDRESS && balance - amount < MINIMUM_LINK_BALANCE) revert InsufficientBalance();
        if (amount < balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```

It is true that the user can call the `transferAndCall()` on the LINK token and execute the transfer in 1 tx. As LINK is an **ERC-677**. Yet for this to be possible `WinnablesTicketManager` must implement an `onTokenTransfer()` that the LINK token would use and it does not implement it. This is another way of fixing this issue.

Duplicate of #277

**Comment by CarlosAlegreUr** [comment]
Escalate

I'm not sure why this issue has been invalidated. When it clearly breaks the:

**1.-** `Winnables admins cannot do anything to prevent a winner from withdrawing their prize`

(This all comes from the section of the contest readme linked in the issue, this one [Q: Please discuss any design choices you made](https://github.com/sherlock-audit/2024-08-winnables-raffles?tab=readme-ov-file#q-please-discuss-any-design-choices-you-made) , I link it again here )

The only reason I can think of it being invalidated is because of what is said
in the same readme a few lines below:

**2.-** `Admins will always keep LINK in the contracts (to pay for CCIP Measages) and in the VRF subscription (to pay for the random numbers)`

There are ways in which the admin can play with the LINK balance of the contracts and lead to users not being able to claim rewards. See another example on other watson's issue #161 . 

Yet it is said the admin will always keep the LINK balance on point but at the same time it is stated that the admin `CANNOT DO ANYTHING`. These statements are contradicting one another.

Anything in my opinion means anything, including altering LINK balance. And I think this finding and #161 should be validated if the reason behind non-reward is the statement **2.-**.

Moreover in the readme, statement **1.-** is under this section: `The principles that must always remain true are`.
And statement **2.-** is under this section: `The following assumptions are to be made about the admin’s behavior without being enforced`

In the first section it says `MUST ALWAYS`, and in the second `WITHOUT BEING ENFORCED`.

So I think statements from the first section have clear priority and thus upon contradiction they should hold.

Making statement **1.-** valid and these issues too.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I'm not sure why this issue has been invalidated. When it clearly breaks the:
> 
> **1.-** `Winnables admins cannot do anything to prevent a winner from withdrawing their prize`
> 
> (This all comes from the section of the contest readme linked in the issue, this one [Q: Please discuss any design choices you made](https://github.com/sherlock-audit/2024-08-winnables-raffles?tab=readme-ov-file#q-please-discuss-any-design-choices-you-made) , I link it again here )
> 
> The only reason I can think of it being invalidated is because of what is said
> in the same readme a few lines below:
> 
> **2.-** `Admins will always keep LINK in the contracts (to pay for CCIP Measages) and in the VRF subscription (to pay for the random numbers)`
> 
> There are ways in which the admin can play with the LINK balance of the contracts and lead to users not being able to claim rewards. See another example on other watson's issue #161 . 
> 
> Yet it is said the admin will always keep the LINK balance on point but at the same time it is stated that the admin `CANNOT DO ANYTHING`. These statements are contradicting one another.
> 
> Anything in my opinion means anything, including altering LINK balance. And I think this finding and #161 should be validated if the reason behind non-reward is the statement **2.-**.
> 
> Moreover in the readme, statement **1.-** is under this section: `The principles that must always remain true are`.
> And statement **2.-** is under this section: `The following assumptions are to be made about the admin’s behavior without being enforced`
> 
> In the first section it says `MUST ALWAYS`, and in the second `WITHOUT BEING ENFORCED`.
> 
> So I think statements from the first section have clear priority and thus upon contradiction they should hold.
> 
> Making statement **1.-** valid and these issues too.
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by mystery0x** [comment]
All admin related issues have been discussed with the HOJ and the sponsor who wished the following governing statements could have been more carefully written and/or omitted:

"The protocol working as expected relies on having an admin creating raffles. It should be expected that the admin will do their job. However it is not expected that the admin can steal funds that should have ended in a raffle participant’s wallet in any conceivable way."

Much as many of the findings suggest good fixes, the conclusion is that they will all be deemed low unless it's beyond the trusted admin control.

**Comment by WangSecurity** [comment]
After additionally considering this issue, the escalation will be accepted and the issue will be validated with medium severity and duplicated with #277. For more details, look into the discussion under #277.

**Comment by WangSecurity** [comment]
Result:
Medium
Duplicate of #277

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [CarlosAlegreUr](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/286/#issuecomment-2332403824): accepted
