### ISSUE TITLE
dimulski - Admin withdrawals of ERC20 tokens can be DOSed by a malicious user

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#297]
dimulski

Medium

# Admin withdrawals of ERC20 tokens can be DOSed by a malicious user

### Summary

In the ``WinnablesTicketManager.sol`` contract the admin should always have some LINK tokens deposited in order to pay for the CCIP messages that are sent from the contract. The contract implements the [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function to allow the admin to withdraw some ERC20 tokens from the contract if he decides to. However there is an incorrect check in the [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function:
```solidity
    function withdrawTokens(address tokenAddress, uint256 amount) external onlyRole(0) {
        IERC20 token = IERC20(tokenAddress);
        uint256 balance = token.balanceOf(address(this));
        if (amount < balance) revert InsufficientBalance();
        token.safeTransfer(msg.sender, amount);
    }
```
As can be seen from the code snippet above, if the admin tries to withdraw an amount of ERC20 tokens that is less than the contract balance the function will revert. This can be exploited by a malicious user, who can see that the admin has called the [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function and frontruns his transaction and sends 1 WEI of LINK token to the contract, this way the [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function will revert, and the admin won't be able to withdraw the funds he has deposited in the ``WinnablesTicketManager.sol`` contract. Frontruning is possible on Avalance.

### Root Cause

Wrong amount check in the [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function. 

### Internal pre-conditions

1. Admin has deposited some amount of LINK tokens in the ``WinnablesTicketMangaer.sol`` contract
2. He wants to withdraw the LINK tokens from the ``WinnablesTicketMangaer.sol`` contract as there is no longer demand for raffles.

### Attack Path

1. Admin deposits 10_000 LINK tokens in the ``WinnablesPrizeManager.sol`` contract.
2. There are a several raffles held, but there is no longer demand for raffles and the admin decides to withdraw the LINK tokens he has previously deposited in the ``WinnablesPrizeManager.sol`` contract. Lets say that there are 9_998 LINK tokens left in the contract.
3. A malicious user sees the admin call to the [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function in the mempool, and frontruns it depositing a single WEI of LINK token to the contract.
4. The [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) function will revert, and the admin won't be able to withdraw the LINK tokens, the malicious actor can perform this attack as many times as he wishes, essentially locking the LINK tokens in the ``WinnablesPrizeManager.sol`` contract. Note that gas on Avalance is cheap. 

### Impact

The admin can't withdraw the LINK tokens that are left in the ``WinnablesTicketManager.sol`` contract, or any other type of ERC20 tokens, that have some dollar value. This may result in a loss of tens of thousands of dollars for the admin. As of writing the report the cost of 1 LINK is around 10 dollars. 

### Mitigation

Change the following check from 
```solidity
if (amount < balance) revert InsufficientBalance();
```
to 
```solidity
if (amount > balance) revert InsufficientBalance();
```

**Comment by AtanasDimulski** [comment]
Escalate,
This issue describes a DOS attack on a function that will be mainly utilized to withdraw excess LINK tokens from the contract by the admin. Utilizing this attack multiple times can easily lock the funds for more than a week. As per the criteria for a valid medium issue: *The issue causes the locking of funds for users for more than a week.*.  Secondly, this is not a griefing for gas attack, as it results in the admin not being able to withdraw funds for a specified period. I believe this issue covers the requirements for a medium issue.

**Comment by sherlock-admin3** [comment]
> Escalate,
> This issue describes a DOS attack on a function that will be mainly utilized to withdraw excess LINK tokens from the contract by the admin. Utilizing this attack multiple times can easily lock the funds for more than a week. As per the criteria for a valid medium issue: *The issue causes the locking of funds for users for more than a week.*.  Secondly, this is not a griefing for gas attack, as it results in the admin not being able to withdraw funds for a specified period. I believe this issue covers the requirements for a medium issue. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by debugging3** [comment]
#183, #432, #444, #485, #492, #500, #575, #582 is dup of this.

**Comment by DemoreXTess** [comment]
I agree with the escalation based on the Sherlock rules. For Denial of Service (DoS) issues, there are two criteria under which an issue can be considered problematic:

> 1) The issue causes locking of funds for users for more than a week.

> 2) The issue impacts the availability of time-sensitive functions (cutoff functions are not considered time-sensitive). 

Focusing on the first criterion, as mentioned by @AtanasDimulski, in this attack vector, an admin's funds can be locked indefinitely by simply sending 1 wei through frontrunning to the smart contract. This is a very low-cost attack vector on the Avalanche network, which makes this submission a valid issue according to the Sherlock rules, specifically due to the following statement:

> If at least one of these are describing the case, the issue can be a Medium.

Therefore, the correct severity for this submission should be Medium.

**Comment by Parth0x108** [comment]
#452 is dup of this

**Comment by Jelev123** [comment]
#78 is dup of this also

**Comment by zanderbytexyz** [comment]
#244 is dup of this

**Comment by mystery0x** [comment]
A low finding at best:

1. There's a workaround to circumvent partial withdrawing.
2. If it mainly concerns LINK, just don't withdraw it. The protocol will be grateful for the generous donation by needing to send in less LINK to the contract to pay for CCIP Measages.

**Comment by AtanasDimulski** [comment]
Hey @mystery0x, thanks for your feedback. However, your first point demonstrates a clear misunderstanding of the issue, it is not about partial withdrawal, due to the way the function is implemented only the full balance can be withdrawn. Your second point doesn't make any sense as well. You can't say that a function is vulnerable so just don't use it. I don't want to sound like a broken record, but there are Sherlock rules in place to help us identify what is an issue and what is not, I have specified them in my first [comment](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/297#issuecomment-2329553880). Thanks for your time.

**Comment by DemoreXTess** [comment]
Another duplicate #603

**Comment by mystery0x** [comment]
Historically, issue pertaining to this optional function which many other protocols won't even care to include is deemed low. Note that it deals with ERC20 tokens accidentally sent to the contract, which is non-rewarded based on Sherlock rule.

**Comment by DemoreXTess** [comment]
@mystery0x We don't validate or invalidate issues based on the historical findings in Sherlock. So your argument is not valid. You can't also know why admin is going to use that function. Protocol uses CCIP which has some LINK costs. Admin should store LINK into the contract and in some point admin may need LINK token, so they need to use that function in order to get the LINK tokens back.

**Comment by DemoreXTess** [comment]
@mystery0x We don't validate or invalidate issues based on the historical findings in Sherlock. You can't also know why admin is going to use that function. Protocol uses Chainlink VRF which has some LINK costs. Admin should store LINK into the contract and in some point admin may need LINK token, so they need to use that function in order to get the LINK tokens back.

**Comment by WangSecurity** [comment]
Thank you for this extensive discussion, but one important part of the DOS rule wasn't mentioned. For this issue to cause a lock of funds for >7 days, this function has to be repeated in almost every block. But, a single iteration of this attack would cause only a DOS of one-block and should be invalid based on this:
> Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by AtanasDimulski** [comment]
Hey @WangSecurity, thanks for your feedback. First of all, I want to mention that is an admin function which is pretty important in my opinion, and I have specified how the admin may lose funds due to his inability to withdraw ERC20 tokens on time. Secondly, as I have mentioned in my first comment I don't believe this can be classified as a griefing for gas attack, as this is not an attack that prevents someone to mint an NFT for ablock. This is time sensitive admin function. Thanks for your time!

**Comment by 0xdanial** [comment]
@WangSecurity thanks for your comment.

I think you misunderstood the issue. There is no need for admin to repeatedly call the withdraw function in almost every block. This issue is about front-running admin withdraw function and blocking the admin from withdrawing funds, not about reverting under normal conditions.

>For this issue to cause a lock of funds for >7 days, this function has to be repeated in almost every block.

This statement is incorrect because attacker can easily set up an MEV bot to front-run the withdraw function whenever admin calls it (not every single block) and transfer `1 wei` of the token to the contract, causing DoS on admin withdrawals.

The cost of this attack is not that significant because, according to the contest readme page:
>On what chains are the smart contracts going to be deployed?
WinnableaPrizeManager will be deployed on Ethereum
WinnablesTicketManager and Tickets will be deployed on Avalanche

the [withdrawTokens()](https://github.com/sherlock-audit/2024-08-winnables-raffles/blob/main/public-contracts/contracts/WinnablesTicketManager.sol#L292-L297) in `WinnablesTicketManager` contract will be deployed on Avalanche, where gas fees are much lower than on Ethereum, which already increases the feasibility of the attack.

According to Sherlock rules:
>The issue causes locking of funds for users for more than a week.

this issue is valid.

**Comment by WangSecurity** [comment]
> Hey @WangSecurity, thanks for your feedback. First of all, I want to mention that is an admin function which is pretty important in my opinion, and I have specified how the admin may lose funds due to his inability to withdraw ERC20 tokens on time. Secondly, as I have mentioned in my first comment I don't believe this can be classified as a griefing for gas attack, as this is not an attack that prevents someone to mint an NFT for ablock. This is time sensitive admin function. Thanks for your time!

Unfortunately, I disagree it's a time-sensitive function as the result of it doesn't change with time, i.e. if you call `withdrawTokens` at X time, you get 9_998 LINK tokens (as in your scenario, but without the attack for the sake of example). Or you can call it at X +1 hour and you get the same amount of tokens. You can call it at X + 1 day and you get the same amount of tokens. Therefore, I believe it's not a time-sensitive function

> This statement is incorrect because attacker can easily set up an MEV bot to front-run the withdraw function whenever admin calls it (not every single block) and transfer 1 wei of the token to the contract, causing DoS on admin withdrawals

Excuse me for the confusion, with saying "in almost every block", what I was trying to say is that this function can be called in every block (essentially, the max frequency it can be called). But, setting MEV bots doesn't mean the attack is not repeated. The single instance of the attack blocks the function for only one block, i.e. the admin can call `withdrawTokens` again in the next block with the same amount + 1 wei and the transaction will go successfully. Therefore, for this to have a larger impact, the attack has to be repeated (with or without the MEV bots).

Therefore, the following rule still applies:
> Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue.

The function is not time-sensitive, the attacker doesn't gain anything and the admin doesn't lose anything, *i.e. the admin can lose tokens only if the attack is repeated perpetually*. Hence, this should remain invalid, planning to reject the escalation.

**Comment by 0xdanial** [comment]
@WangSecurity, I agree this is not a time-sensitive function since the amount of LINK tokens doesn’t change. However, we cannot predict how much LINK the admin will transfer. The admin might rely on this withdrawal function to transfer a large amount of LINK, and blocking withdrawals could result in value loss due to price fluctuations over time.

Even if we consider this function non-time-sensitive, it remains one of the core functions in the contract. According to Sherlock’s rules:
>loss of functionality is not considered a loss of protocol revenue, nevertheless issues involving opportunity loss may be valid issues (for example, due to a loss of core functionality).

As you mentioned, the admin does not lose anything, but blocking this function through an MEV bot could be considered a valid Medium issue.

This can be easily bypassed:
>admin can call withdrawTokens again in the next block with the same amount + 1 wei and the transaction will go successfully.

attacker MEV bot can transfer random amounts in each transaction (e.g., 1 wei, 3 wei, 5 wei).

Attempting to find a workaround to dismiss the issue isn’t a fair approach. By that logic, any upgradable contract would have no issues because the admin could always upgrade and fix problems later.

Best regards.

**Comment by WangSecurity** [comment]
> attacker MEV bot can transfer random amounts in each transaction

Unfortunately, in the previous comment, I explained that based on the rules, it's not a valid scenario and is considered a DOS of a single block. Hence, the admin can withdraw tokens in the next block. 

The decision remains, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/297/#issuecomment-2329553880): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Winnables/public-contracts/pull/6
