### ISSUE TITLE
irresponsible - Malicious user can cancel raffle with incorrect chain selector to Make the prize be stuck

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-winnables-raffles-judging#357]
irresponsible

High

# Malicious user can cancel raffle with incorrect chain selector to Make the prize be stuck

### Summary

Malicious user can cancel raffle with incorrect chain selector to Make the prize be stuck

### Root Cause

in WinnablesTicketManager.sol ln 278
https://github.com/Winnables/public-contracts/blob/267dd06e2d5636f30e3311c46ed24b76ac6614c5/contracts/WinnablesTicketManager.sol#L278

any user can cancel a raffle if it is eligible to be canceled. When calling the function `cancelRaffle`, the function sets the raffles status to canceled and then the function sends a ccip message to the chosen chain, this message will then call the ccip receive on the chosen chain and cancel the raffle and then unlocking the prize. this can be observed below 
```solidity
    function cancelRaffle(address prizeManager, uint64 chainSelector, uint256 raffleId) external {
        _checkShouldCancel(raffleId);

        _raffles[raffleId].status = RaffleStatus.CANCELED;
        _sendCCIPMessage(
            prizeManager,
            chainSelector,
            abi.encodePacked(uint8(CCIPMessageType.RAFFLE_CANCELED), raffleId)
        );
        IWinnablesTicket(TICKETS_CONTRACT).refreshMetadata(raffleId);
    }
```
The problem is that the user is free to pick the chainSelector, this is a problem because the user can input the incorrect chain and the message will be sent to a chain where there is no contract. This will cause the raffle to not be able to be canceled on the correct destination chain and therefore the prize will never be unlocked. This means any malicious user can essentially lock the prize in the contract forever.

### Internal pre-conditions

1. the raffle should be eligible to be canceled

### External pre-conditions

none

### Attack Path

1. the raffle did not reach enough ticket sales
2. malicious user calls `cancelRaffle` on the WinnablesTicketManager contract with the incorrect chainSelector
3. the users will be able to refund their ticket proceeds
4. the winnablesPrizeManager contract on the correct chain will never receive the ccip message and the prize will remain locked

### Impact

Malicious user can easily lock the prize from the raffle forever 

### Mitigation

do not allow users to select the chainSelector when calling `cancelRaffle`

Duplicate of #50

**Comment by ArnieSec** [comment]
Escalate

The issue should not be a duplicate of issue #50 

Issue 50's root cause is in the function `propagateRaffleWinner`

The root cause of this issue comes from the `cancelRaffle` function. While the issues are similar in nature, they are separate issues and this can be further confirmed because fixing issue 50 will not fix this issue. Therefore I would kindly like to escalate and try to de-duplicate this issue from issue 50, this should be an entirely separate issue.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The issue should not be a duplicate of issue #50 
> 
> Issue 50's root cause is in the function `propagateRaffleWinner`
> 
> The root cause of this issue comes from the `cancelRaffle` function. While the issues are similar in nature, they are separate issues and this can be further confirmed because fixing issue 50 will not fix this issue. Therefore I would kindly like to escalate and try to de-duplicate this issue from issue 50, this should be an entirely separate issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by philbugcatcher** [comment]
Agreed with the escalation. https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/48 was also tagged as a duplicate, but refers to a different issue.

**Comment by WangSecurity** [comment]
But, as I understand, the issue in #50 and this report is pretty much the same, besides the fact that it happens in different functions. 
They have the same root cause -- no validation of the prize manager and chain selector
They have the same scenario and the same impact. The only difference is occurring in different functions, therefore, the fix can be the same, but still they have to be fixed separately.

But, I believe they should be considered duplicates:
> If the following issues appear in multiple places, even in different contracts. In that case, they may be considered to have the same root cause.
Issues with the same logic mistake

Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #50

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ArnieSec](https://github.com/sherlock-audit/2024-08-winnables-raffles-judging/issues/357/#issuecomment-2330528560): rejected
